import { Product, FAQItem } from './types';

export const BRANDS = [
  'Pirelli',
  'Michelin',
  'Goodyear',
  'Bridgestone',
  'Continental',
  'Dunlop',
  'Firestone',
  'Hankook',
];

export const PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Pneu Pirelli 175/70 R13',
    brand: 'Pirelli',
    measure: '175/70 R13',
    rim: 13,
    category: 'Carro de passeio',
    application: 'veículos compactos',
    specs: [
      'Modelo: Cinturato P1',
      'Índice de Carga: 82 (475 kg por pneu)',
      'Índice de Velocidade: T (Até 190 km/h)',
      'Estrutura: Radial (Tubeless - Sem câmara)',
      'Durabilidade, aderência em piso molhado e excelente eficiência de combustível.',
    ],
    status: 'Disponibilidade sob consulta',
    image: 'https://images.unsplash.com/photo-1578844251758-2f71da64c96f?auto=format&fit=crop&q=80&w=600',
  },
  {
    id: '2',
    name: 'Pneu Goodyear 175/65 R14',
    brand: 'Goodyear',
    measure: '175/65 R14',
    rim: 14,
    category: 'Carro de passeio',
    application: 'hatch e sedan compacto',
    specs: [
      'Modelo: Assurance MaxLife',
      'Índice de Carga: 82 (475 kg por pneu)',
      'Índice de Velocidade: H (Até 210 km/h)',
      'Estrutura: Radial (Tubeless - Sem câmara)',
      'Maior quilometragem da categoria, excelente tração e frenagem otimizada.',
    ],
    status: 'Disponibilidade sob consulta',
    image: 'https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&q=80&w=600',
  },
  {
    id: '3',
    name: 'Pneu Continental 185/60 R14',
    brand: 'Continental',
    measure: '185/60 R14',
    rim: 14,
    category: 'Carro de passeio',
    application: 'veículos compactos e médios',
    specs: [
      'Modelo: PowerContact 2',
      'Índice de Carga: 82 (475 kg por pneu)',
      'Índice de Velocidade: H (Até 210 km/h)',
      'Estrutura: Radial (Tubeless - Sem câmara)',
      'Segurança extra para o dia a dia, rodar silencioso e excelente custo-benefício.',
    ],
    status: 'Disponibilidade sob consulta',
    image: 'https://images.unsplash.com/photo-1551524559-8af4e6624178?auto=format&fit=crop&q=80&w=600',
  },
  {
    id: '4',
    name: 'Pneu Michelin 185/65 R15',
    brand: 'Michelin',
    measure: '185/65 R15',
    rim: 15,
    category: 'Carro de passeio',
    application: 'hatch, sedan e veículos urbanos',
    specs: [
      'Modelo: Energy XM2+',
      'Índice de Carga: 88 (560 kg por pneu)',
      'Índice de Velocidade: H (Até 210 km/h)',
      'Estrutura: Radial (Tubeless - Sem câmara)',
      'Altamente resistente a impactos e cortes, frenagem imediata em piso molhado.',
    ],
    status: 'Disponibilidade sob consulta',
    image: 'https://images.unsplash.com/photo-1486006920555-c77dce18193b?auto=format&fit=crop&q=80&w=600',
  },
  {
    id: '5',
    name: 'Pneu Pirelli 195/55 R15',
    brand: 'Pirelli',
    measure: '195/55 R15',
    rim: 15,
    category: 'Carro de passeio',
    application: 'veículos médios',
    specs: [
      'Modelo: Cinturato P7',
      'Índice de Carga: 85 (515 kg por pneu)',
      'Índice de Velocidade: V (Até 240 km/h)',
      'Estrutura: Radial (Tubeless - Sem câmara)',
      'Desempenho esportivo, máxima segurança em curvas e frenagens de emergência.',
    ],
    status: 'Disponibilidade sob consulta',
    image: 'https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?auto=format&fit=crop&q=80&w=600',
  },
  {
    id: '6',
    name: 'Pneu Bridgestone 195/65 R15',
    brand: 'Bridgestone',
    measure: '195/65 R15',
    rim: 15,
    category: 'Carro de passeio',
    application: 'sedan e veículos médios',
    specs: [
      'Modelo: Ecopia EP150',
      'Índice de Carga: 91 (615 kg por pneu)',
      'Índice de Velocidade: H (Até 210 km/h)',
      'Estrutura: Radial (Tubeless - Sem câmara)',
      'Desenvolvido com foco ecológico, redução no consumo de combustível e emissão de CO2.',
    ],
    status: 'Disponibilidade sob consulta',
    image: 'https://images.unsplash.com/photo-1506015391300-4802dc74de2e?auto=format&fit=crop&q=80&w=600',
  },
  {
    id: '7',
    name: 'Pneu Goodyear 205/55 R16',
    brand: 'Goodyear',
    measure: '205/55 R16',
    rim: 16,
    category: 'Carro de passeio',
    application: 'sedan, hatch médio e veículos premium',
    specs: [
      'Modelo: Eagle F1 Asymmetric 5',
      'Índice de Carga: 91 (615 kg por pneu)',
      'Índice de Velocidade: V (Até 240 km/h)',
      'Estrutura: Radial (Tubeless - Sem câmara)',
      'Super alta performance, aderência excepcional e menor distância de parada na chuva.',
    ],
    status: 'Disponibilidade sob consulta',
    image: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&q=80&w=600',
  },
  {
    id: '8',
    name: 'Pneu Continental 205/60 R16',
    brand: 'Continental',
    measure: '205/60 R16',
    rim: 16,
    category: 'Carro de passeio',
    application: 'sedan e veículos familiares',
    specs: [
      'Modelo: ContiPremiumContact 6',
      'Índice de Carga: 92 (630 kg por pneu)',
      'Índice de Velocidade: V (Até 240 km/h)',
      'Estrutura: Radial (Tubeless - Sem câmara)',
      'Nível máximo de frenagem com excelente maciez e estabilidade direcional avançada.',
    ],
    status: 'Disponibilidade sob consulta',
    image: 'https://images.unsplash.com/photo-1611245329358-ac8a346f0995?auto=format&fit=crop&q=80&w=600',
  },
  {
    id: '9',
    name: 'Pneu Michelin 215/55 R17',
    brand: 'Michelin',
    measure: '215/55 R17',
    rim: 17,
    category: 'Carro de passeio',
    application: 'sedan, SUV compacto e veículos médios',
    specs: [
      'Modelo: Primacy 4',
      'Índice de Carga: 94 (670 kg por pneu)',
      'Índice de Velocidade: W (Até 270 km/h)',
      'Estrutura: Radial (Tubeless - Sem câmara)',
      'Excelente desempenho de frenagem mesmo quando usado e excelente durabilidade geral.',
    ],
    status: 'Disponibilidade sob consulta',
    image: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&q=80&w=600',
  },
  {
    id: '10',
    name: 'Pneu Pirelli 225/45 R17',
    brand: 'Pirelli',
    measure: '225/45 R17',
    rim: 17,
    category: 'Carro de passeio',
    application: 'veículos esportivos e premium',
    specs: [
      'Modelo: P Zero',
      'Índice de Carga: 91 (615 kg por pneu)',
      'Índice de Velocidade: Y (Até 300 km/h)',
      'Estrutura: Radial (Tubeless - Sem câmara)',
      'Referência mundial no segmento de Ultra Alta Performance (UHP) para carros esportivos.',
    ],
    status: 'Disponibilidade sob consulta',
    image: 'https://images.unsplash.com/photo-1606576921319-58fffa67d13e?auto=format&fit=crop&q=80&w=600',
  },
  {
    id: '11',
    name: 'Pneu Bridgestone 225/55 R18',
    brand: 'Bridgestone',
    measure: '225/55 R18',
    rim: 18,
    category: 'SUV e utilitário leve',
    application: 'SUVs e veículos maiores',
    specs: [
      'Modelo: Dueler H/P Sport',
      'Índice de Carga: 98 (750 kg por pneu)',
      'Índice de Velocidade: V (Até 240 km/h)',
      'Estrutura: Radial (Tubeless - Sem câmara)',
      'Tração impecável, estabilidade direcional em rodovias e excelente escoamento de água.',
    ],
    status: 'Disponibilidade sob consulta',
    image: 'https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&q=80&w=600',
  },
  {
    id: '12',
    name: 'Pneu Goodyear 235/60 R18',
    brand: 'Goodyear',
    measure: '235/60 R18',
    rim: 18,
    category: 'SUV e utilitário leve',
    application: 'SUVs e utilitários leves',
    specs: [
      'Modelo: EfficientGrip SUV',
      'Índice de Carga: 103 (875 kg por pneu)',
      'Índice de Velocidade: V (Até 240 km/h)',
      'Estrutura: Radial (Tubeless - Sem câmara)',
      'Alta tecnologia no composto de sílica para reduzir o consumo de combustível e aumentar a aderência.',
    ],
    status: 'Disponibilidade sob consulta',
    image: 'https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?auto=format&fit=crop&q=80&w=600',
  },
];

export const FAQS: FAQItem[] = [
  {
    question: 'O site vende pneus diretamente?',
    answer:
      'Não. Nosso site atua estritamente como um catálogo informativo de pneus multimarcas para consulta de modelos e especificações técnicas. Todas as consultas de disponibilidade, preços e entrega ocorrem exclusivamente através do nosso atendimento humano via WhatsApp.',
  },
  {
    question: 'Como funciona o pagamento?',
    answer:
      'Este site não realiza nenhuma cobrança, pagamento online,Pix, boleto, cartão, checkout ou intermediação financeira direta. O portal não coleta dados bancários ou senhas. As formas de pagamento disponíveis são informadas e combinadas exclusivamente pelo atendimento humano, de forma transparente após a confirmação do produto e disponibilidade.',
  },
  {
    question: 'O WhatsApp representa compra automática?',
    answer:
      'Não. O contato pelo WhatsApp não representa compra automática ou reserva imediata. Preços, disponibilidade de estoque, entrega e formas de pagamento devem ser expressamente confirmados diretamente com a nossa equipe.',
  },
  {
    question: 'Como funciona a disponibilidade dos produtos?',
    answer:
      'Devido à alta rotatividade, a entrega e a disponibilidade física de estoque dos pneus publicados no site estão sujeitas à confirmação no momento do atendimento. Recomendamos consultar nossa equipe pelo WhatsApp para confirmar a presença do pneu desejado.',
  },
  {
    question: 'A Pneu Center Brasil possui marcas oficiais?',
    answer:
      'A Pneu Center Brasil é uma revendedora multimarcas independente. Os nomes e marcas comerciais citados (como Pirelli, Michelin, Goodyear, Bridgestone, Continental, Dunlop, Firestone e Hankook) pertencem aos seus respectivos fabricantes e são utilizados exclusivamente para identificação dos modelos e especificações técnicas dos produtos. Não possuímos vínculo societário, parceria oficial ou representação institucional com os fabricantes listados.',
  },
  {
    question: 'Como funciona a garantia dos pneus?',
    answer:
      'Os produtos seguem as garantias legais aplicáveis e, quando houver, as condições de garantia informadas pelo respectivo fabricante ou distribuidor. As regras específicas de garantia podem variar conforme marca, modelo e análise técnica, sendo explicadas pelo atendimento de forma transparente.',
  },
];
